import type { Metadata } from 'next'
import { LegalList, LegalPage, LegalLink, createLegalMetadata } from '@/components/legal-page'

export const metadata: Metadata = createLegalMetadata('Privacy Policy', 'How Shepherds Not Sheep may collect and use information while the organization is in development.')

export default function PrivacyPage() {
  return <LegalPage eyebrow="Privacy" title="A careful approach to your information." description="This plain-English privacy policy explains how Shepherds Not Sheep may handle information submitted through this website while the organization is in development." sections={[
    { title: 'Information we may collect', children: <><p>Depending on the page or form you use, we may receive information you choose to provide, such as your name, email address, phone number, message content, veteran-related contact information, volunteer interests, donation details, or newsletter preferences.</p><p>We may also receive basic browser, device, usage, and analytics information, such as pages visited, approximate location derived from an IP address, referral source, and general interaction data.</p></> },
    { title: 'Why we collect information', children: <><p>Information may be collected so we can respond to questions, understand requests for veteran assistance, coordinate future volunteer or program interest, communicate updates, improve the website, and prepare for future donation or newsletter functions.</p><p>Please do not submit highly sensitive medical, financial, Social Security, classified, or similarly confidential information through a general website form.</p></> },
    { title: 'How information may be used', children: <LegalList items={['To respond to messages and requests you send us.', 'To review interest in future programs, volunteer opportunities, or community involvement.', 'To maintain, secure, troubleshoot, and improve the website.', 'To send updates when you have asked to receive them or when a communication feature is active.', 'To meet legal, safety, or operational requirements when applicable.']} /> },
    { title: 'Sharing and sale of information', children: <><p>We do not sell personal information. We may share information with service providers that are necessary to operate the website, such as hosting, form, email, analytics, security, or payment providers when those features are enabled.</p><p>We may also disclose information when reasonably necessary to protect the website, respond to lawful requests, address safety concerns, or protect rights and property.</p></> },
    { title: 'Cookies and analytics', children: <p>The website may use cookies or similar technologies for essential functions, preferences, security, and analytics. Analytics information is used to understand general website use and improve the experience. Browser settings may allow you to limit or block cookies, though some features may not work as intended.</p> },
    { title: 'Retention and security', children: <><p>We retain information only for as long as reasonably needed for the purpose it was collected, ongoing communication, operational records, legal requirements, or legitimate organizational needs. Retention periods may change as the organization and its systems develop.</p><p>We use reasonable safeguards appropriate to the website and the information handled. No website, transmission, or storage system can be guaranteed completely secure.</p></> },
    { title: 'Third-party links and children\'s privacy', children: <><p>This website may link to third-party websites or resources. Their privacy practices are controlled by their own policies, not this one.</p><p>This website is not directed to children under 13, and we do not knowingly request personal information from children under 13 through general website forms.</p></> },
    { title: 'Questions about privacy', children: <p>For privacy questions or requests, please use the <LegalLink href="/contact">contact page</LegalLink>. A dedicated privacy contact method may be added as the organization develops.</p> },
  ]} />
}
