import type { Metadata } from 'next'
import { Container, PageHero, SectionHeading, StatusRow } from '@/components/site-sections'
import { DonationForm } from '@/components/donation-form'

export const metadata: Metadata = { title: 'Donate' }

type DonatePageProps = { searchParams: Promise<{ success?: string; canceled?: string }> }

export default async function DonatePage({ searchParams }: DonatePageProps) {
  const params = await searchParams
  return <><PageHero eyebrow="Support the mission" title="Give with intention." description="Your support helps Shepherds Not Sheep build a responsible, transparent community for veterans. Choose a one-time or monthly gift and complete it securely through Stripe." /><section className="bg-cream py-16 sm:py-24"><Container><div className="grid gap-12 lg:grid-cols-[0.85fr_1.15fr] lg:items-start lg:gap-24"><div><SectionHeading eyebrow="Make a gift" title="A practical contribution to the foundation." /><p className="mt-6 text-base leading-8 text-charcoal/70">Every donation is recorded with its intended program and updated after Stripe confirms payment. We are building the organization carefully, with clear records and no claims beyond what is verified.</p><p className="mt-4 rounded-sm border border-navy/15 bg-[#f4f0e8] p-4 text-sm leading-7 text-charcoal/70">Shepherds Not Sheep is an organization in formation. We have not confirmed 501(c)(3) status, and <strong className="font-semibold text-navy">donations are not tax-deductible at this time.</strong></p><div className="mt-10 border-t border-navy/15"><StatusRow title="One-time donations" status="Live" description="Make a single contribution through secure Stripe Checkout." /><StatusRow title="Monthly support" status="Live" description="Provide recurring support for future operating needs." /><StatusRow title="Program direction" status="Choose" description="Select where you would like your gift directed." /></div></div><DonationForm success={params.success === '1'} canceled={params.canceled === '1'} /></div></Container></section><section className="border-y border-navy/10 bg-[#ebe6dc] py-16 sm:py-24"><Container><div className="mx-auto max-w-3xl text-center"><p className="eyebrow text-olive">Stewardship first</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.04em] text-navy sm:text-5xl">Credibility is built in the open.</h2><p className="mt-6 text-base leading-8 text-charcoal/70">We do not claim tax status, program outcomes, or funding relationships before they are confirmed and ready to publish. Visit our transparency page for the organization&apos;s current development status.</p></div></Container></section></>
}
